name: 'Giphy PR Comment- Test Action'
description: 'Add a Giphy GIF as comment to a new PR.'

inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  giphy-api-key:
    description: 'Giphy API Key'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'

  branding:
    icon: 'activity'
    color: 'green'
